spring.application.name=Fleet
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/fleet
spring.datasource.username=root
spring.datasource.password=Yashit@2004

#tomacat server
server.servlet.context-path=/api/v1

#jwt secret key
jwt.secret_key=jfbifbewf283ry89fnewifb932ewkjf3wirq3oun83ry32rnnkjcnewiuufu38737403bejcnww89ancwiur32rbewjfb389rh12dkadwbq9r2awf9832r32fhlewiugfwo87fg

#twilio