#Application
spring.application.name=Fleet
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#MySQL DB
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

#tomacat server
server.servlet.context-path=/api/v1

#jwt secret key
jwt.secret_key=${JWT_SECRET_KEY}

#twilio
twilio.ACCOUNT_SID = ${TWILIO_ACCOUNT_SID}
twilio.AUTH_TOKEN = ${TWILIO_AUTH_TOKEN}
twilio.WHATSAPP_FROM =${TWILIO_WHATSAPP_FROM}

#frontend
frontend.url = ${FRONTEND_URL}

# Tell Spring Boot to use the port assigned by Railway, defaulting to 8080 locally
server.port=${PORT:8080}
spring.main.lazy-initialization=true